apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: y6nz109p5-python-gitops
  description: This is GitOps manifest for y6nz109p5-python   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=y6nz109p5-python
    backstage.io/kubernetes-id: y6nz109p5-python 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: y6nz109p5-python
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:y6nz109p5-python
